/*0===========================================================================
**
** File:       syserr.h
**
** Purpose:    System error constants.
**
**
**
**
** Date:       August 10, 1993
**
** Author:     Alan D. Graves
**
**============================================================================
*/

#ifndef SYSERR_H
#define SYSERR_H

/*==========================================================================
|
|  constants
|
===========================================================================*/

// General Codes

#define ERR_NONE                       0     // Success, Okay, etc.
#define ERR_BUFFER                     -1    // circular buffer error

#endif

